config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, NULL: false
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def new
  #   @bookmark = Bookmark.new
  #   @list = List.find(params[:list_id])
  # end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment).merge(params.permit(:list_id))
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark], html: { class: "w-100"} do |f| %>
  <%= f.association :movie, input_html: { class: 'select2' }  %>
  <%= f.input :comment %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file%>
  <%= f.submit class:"btn btn-primary"%>
<% end %>

app/views/lists/index.html.erb
<% background_url = "https://images.unsplash.com/photo-1478720568477-152d9b164e26?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218MHx8Y2luZW1hfHx8fHx8MTYzNjcwOTI4Ng&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1600" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= background_url %>);">
  <div class="container">
    <h1>Create your own movie list!</h1>
    <p>Save all your favourite movies in a few clicks.</p>
  </div>
</div>

<div class="container py-5">
  <h1>Check out your lists</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>');">
            <i class="fas fa-film"></i> <%= list.name %>
        </div>
      <% end %>
    <% end %>

    <%= link_to new_list_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
        <i class="fas fa-plus"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<% background_url = "https://images.unsplash.com/photo-1543428072-d3352b8a3219?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218MHx8bGlzdHx8fHx8fDE2MzY3MjM3MjI&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1600" %>
<div class="new-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= background_url %>);">
  <div class="container">
    <h1>New List</h1>
  </div>
</div>
<div class="container py-3">
  <%= render "form", list: @list %>
  <hr>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container py-5">
  <div class="row">
    <div class="col-9">
      <div class="cards">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-movie">
            <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="bookmark.movie.title">
            <div class="card-body">
              <div class="card-group">
                <h4 class="card-title"><%= bookmark.movie.title %></h4>
                <p class="card-rating"><%= bookmark.movie.rating %><i class="fas fa-star"></i></p>
              </div>
              <p class="card-overview"><%= bookmark.movie.overview %></p>
              <div class="card-group">
                <p class="card-comment"><em><i class="fas fa-quote-left"></i> <%= bookmark.comment %></em></p>
                <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="card-movie card-add p-3">
          <h2>Add movie</h2>
          <%= render "bookmarks/form", { list: @list, bookmark: @bookmark } %>
        </div>
      </div>
    </div>
    <div class="col-3">
      <% @list.reviews.each do |review| %>
        <p><%= review.comment %> <%= '⭐️' * review.rating %>
      <% end %>
      <hr>
      <h2>Add review</h2>
      <%= render "reviews/form", { list: @list, review: @review } %>
    </div>
  </div>


</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-info' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <%= link_to lists_path, class: "nav-link navbar-brand" do %>
    <img src="https://image.flaticon.com/icons/png/512/1101/1101761.png" /> Movie List
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
        <%= link_to "Add List", new_list_path, class: "btn btn-info" %>
      </li>
    </ul>
  </div>
</div>